apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: clientapp-2
  name: clientapp-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clientapp-2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: clientapp-2
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - args:
            - --insecure
            - --clientappio-api-address
            - supernode-2:9095
          image: adityapgupta/flower-client-2:latest
          name: clientapp-2
          ports:
            - containerPort: 9095
              protocol: TCP
          resources:
            limits:
              cpu: "2"
      restartPolicy: Always
