apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: superlink
  name: superlink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: superlink
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: superlink
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - args:
            - --insecure
            - --isolation
            - process
          image: flwr/superlink:1.15.2
          name: superlink
          ports:
            - containerPort: 9093
              protocol: TCP
      restartPolicy: Always
